name: dist-check
on: [push, pull_request]
jobs:
  ubuntu-latest_dist-mini:
    runs-on: ubuntu-latest
    name: Ubuntu-latest distcheck with minimal requirements
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - run: sudo apt-get update
    - name: Install minimal dependencies
      run: sudo apt-get install -y cmake ninja-build libxml2-utils xsltproc docbook-xsl
    - run: |
        echo "ROOT_DIR=$GITHUB_WORKSPACE/.." >> $GITHUB_ENV
    - name: Create Directories
      run: |
        pwd
        mkdir $ROOT_DIR/inst
        mkdir build
    - name: Configure GnuCash-docs
      run: |
        cd build
        cmake -G Ninja -DCMAKE_INSTALL_PREFIX=$ROOT_DIR/inst $GITHUB_WORKSPACE -DWITH_MOBI=ON
    - name: Build distribution
      run: |
        cd build
        ninja dist
    - name: Check distribution
      run: |
        cd build
        ninja distcheck
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: TestLog
        path: ${{ github.workspace }}/build/Testing/Temporary/LastTest.log
